name: Android CI

on: 
  workflow_dispatch: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
    - name: 检查
      uses: actions/checkout@v3

    - name: 安装 JDK 11
      uses: actions/setup-java@v3
      with: 
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: 给予gradlew执行许可
      run: |
        sudo chmod +x gradlew

    - name: 编译
      run: |
        ./gradlew build
    
    - name: 上传
      uses: actions/upload-artifact@v3
      with: 
        path: app/build/outputs/apk/release/*.apk
